Repository hmcts/sscs-cor-backend, pull requests merged in 2019-05, with the labels that each got.

#314 use variable in url
  infrastructure/main.tf
Labels: ns:sscs-cor-backend-pr-314

#319 SSCS-5566 Answers pdf not getting updated
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/sscscorbackend/TriggerCohEventsTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/sscscorbackend/CohEventsTest.java
  src/main/java/uk/gov/hmcts/reform/sscscorbackend/coheventmapper/CohEventActionRunner.java
  src/main/java/uk/gov/hmcts/reform/sscscorbackend/coheventmapper/actions/AnswerSubmittedEventAction.java
  src/main/java/uk/gov/hmcts/reform/sscscorbackend/coheventmapper/actions/CohEventAction.java
  src/main/java/uk/gov/hmcts/reform/sscscorbackend/coheventmapper/actions/DeadlineElapsedEventAction.java
  src/main/java/uk/gov/hmcts/reform/sscscorbackend/coheventmapper/actions/DeadlineExtendedEventAction.java
  src/main/java/uk/gov/hmcts/reform/sscscorbackend/coheventmapper/actions/DeadlineExtensionDeniedEventAction.java
  src/main/java/uk/gov/hmcts/reform/sscscorbackend/coheventmapper/actions/DeadlineExtensionGrantedEventAction.java
  src/main/java/uk/gov/hmcts/reform/sscscorbackend/coheventmapper/actions/DeadlineReminderEventAction.java
  src/main/java/uk/gov/hmcts/reform/sscscorbackend/coheventmapper/actions/DecisionIssuedEventAction.java
  src/main/java/uk/gov/hmcts/reform/sscscorbackend/coheventmapper/actions/DecisionRejectedEventAction.java
  src/main/java/uk/gov/hmcts/reform/sscscorbackend/coheventmapper/actions/HearingRelistedAction.java
  src/main/java/uk/gov/hmcts/reform/sscscorbackend/coheventmapper/actions/QuestionRoundEndedAction.java
  src/main/java/uk/gov/hmcts/reform/sscscorbackend/coheventmapper/actions/QuestionRoundIssuedEventAction.java
  src/main/java/uk/gov/hmcts/reform/sscscorbackend/service/pdf/data/PdfData.java
  src/test/java/uk/gov/hmcts/reform/sscscorbackend/coheventmapper/CohEventActionRunnerTest.java
  src/test/java/uk/gov/hmcts/reform/sscscorbackend/coheventmapper/action/AnswerSubmittedEventActionTest.java
  src/test/java/uk/gov/hmcts/reform/sscscorbackend/coheventmapper/action/DeadlineElapsedEventActionTest.java
  src/test/java/uk/gov/hmcts/reform/sscscorbackend/coheventmapper/action/DecisionIssuedEventActionTest.java
  src/test/java/uk/gov/hmcts/reform/sscscorbackend/coheventmapper/action/HearingRelistedActionTest.java
  src/test/java/uk/gov/hmcts/reform/sscscorbackend/coheventmapper/action/QuestionRoundIssuedEventActionTest.java
Labels: ns:sscs-cor-backend-pr-319

#323 Merge in changes on demo branch before rebasing that.
  build.gradle
  infrastructure/variables.tf
Labels: ns:sscs-cor-backend-pr-323

#324 idam_url is set in the main.tf and uses '${local.local_env}' to set
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/preview.tfvars
  infrastructure/saat.tfvars
  infrastructure/variables.tf
Labels: ns:sscs-cor-backend-pr-324

#326 Separate caseworker and from email address
  infrastructure/main.tf
  infrastructure/variables.tf
  src/integrationTest/java/uk/gov/hmcts/reform/sscscorbackend/RecordTribunalViewResponseTest.java
  src/main/java/uk/gov/hmcts/reform/sscscorbackend/service/email/CorEmailService.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/sscscorbackend/service/email/CorEmailServiceTest.java
Labels: ns:sscs-cor-backend-pr-326

#327 Idam prod url
  infrastructure/main.tf
Labels: ns:sscs-cor-backend-pr-327

#328 set to prod value
  infrastructure/prod.tfvars
Labels: ns:sscs-cor-backend-pr-328

#329 Fix prod redirect url
  charts/sscs-cor-backend/values.template.yaml
  infrastructure/aat.tfvars
  infrastructure/preview.tfvars
  src/main/resources/application.yaml
Labels: ns:sscs-cor-backend-pr-329

#330 Fix prod redirect url
  charts/sscs-cor-backend/values.template.yaml
  src/main/resources/application.yaml
Labels: ns:sscs-cor-backend-pr-330

#333 Adding prod values for emails
  infrastructure/prod.tfvars
Labels: ns:sscs-cor-backend-pr-333

#335 think it needs this
  infrastructure/output.tf
Labels: ns:sscs-cor-backend-pr-335

#341 Fix answered date for question summaries
  src/integrationTest/java/uk/gov/hmcts/reform/sscscorbackend/stubs/CohStub.java
  src/main/java/uk/gov/hmcts/reform/sscscorbackend/service/QuestionService.java
Labels: ns:sscs-cor-backend-pr-341
