Repository hmcts/sscs-cor-backend, pull requests merged in 2019-04, with the labels that each got.

#266 Upgrade common library to 0.0.157
  build.gradle
Labels: ns:sscs-cor-backend-pr-266

#285 Update versions
  build.gradle
Labels: ns:sscs-cor-backend-pr-285

#286 Reenable ignored test
  src/functionalTest/java/uk/gov/hmcts/reform/sscscorbackend/EvidenceUploadTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/sscscorbackend/SscsCorBackendRequests.java
Labels: ns:sscs-cor-backend-pr-286

#297 Upgrade common modules.
  build.gradle
Labels: ns:sscs-cor-backend-pr-297

#304 SSCS-5223 Panel listing notes in CCD
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/sscscorbackend/BaseFunctionTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/sscscorbackend/CohEventsTests.java
  src/functionalTest/java/uk/gov/hmcts/reform/sscscorbackend/CohRequests.java
  src/main/java/uk/gov/hmcts/reform/sscscorbackend/controllers/coheventmapper/HearingRelistedAction.java
  src/test/java/uk/gov/hmcts/reform/sscscorbackend/DataFixtures.java
  src/test/java/uk/gov/hmcts/reform/sscscorbackend/controllers/coheventmapper/HearingRelistedActionTest.java
  src/test/java/uk/gov/hmcts/reform/sscscorbackend/thirdparty/ccd/api/CcdHistoryEventTest.java
Labels: ns:sscs-cor-backend-pr-304

#310 Fix issuing questions was failing when questions contained &nbsp;
  src/main/resources/templates/answers.html
  src/main/resources/templates/evidenceDescription.html
  src/main/resources/templates/onlineHearingSummary.html
  src/main/resources/templates/personalStatement.html
  src/main/resources/templates/questions.html
  src/main/resources/templates/tribunalsView.html
Labels: ns:sscs-cor-backend-pr-310
