Repository hmcts/sscs-cor-backend, pull requests merged in 2019-12, with the labels that each got.

#520 Added intellij settings
  README.md
Labels: ns:sscs-cor-backend-pr-520

#513 SSCS-6859 Convert MYA documents and images to pdf
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  build.gradle
  charts/sscs-cor-backend/Chart.yaml
  charts/sscs-cor-backend/values.yaml
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/variables.tf
  src/functionalTest/java/uk/gov/hmcts/reform/sscscorbackend/EvidenceUploadTest.java
  src/main/java/uk/gov/hmcts/reform/sscscorbackend/Application.java
  src/main/java/uk/gov/hmcts/reform/sscscorbackend/config/PdfServiceConfiguration.java
  src/main/java/uk/gov/hmcts/reform/sscscorbackend/service/evidence/EvidenceUploadService.java
  src/main/java/uk/gov/hmcts/reform/sscscorbackend/thirdparty/documentmanagement/DocumentManagementService.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/sscscorbackend/service/evidence/EvidenceUploadServiceTest.java
Labels: ns:sscs-cor-backend-pr-513

#525 Disable ASE on AAT
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/preview.tfvars
  infrastructure/prod.tfvars
  infrastructure/saat.tfvars
  infrastructure/variables.tf
Labels: ns:sscs-cor-backend-pr-525

#522 SSCS 6853 added sscs shared infra instrument key
  Jenkinsfile_CNP
  infrastructure/main.tf
Labels: ns:sscs-cor-backend-pr-522

#533 Sscs 6853 turn on alerts
  infrastructure/main.tf
Labels: ns:sscs-cor-backend-pr-533

#526 Feature/sscs 6919 statements
  build.gradle
  src/main/java/uk/gov/hmcts/reform/sscscorbackend/service/pdf/StoreAppellantStatementService.java
  src/main/java/uk/gov/hmcts/reform/sscscorbackend/service/pdf/StorePdfService.java
  src/test/java/uk/gov/hmcts/reform/sscscorbackend/service/pdf/StoreAppellantStatementServiceTest.java
Labels: ns:sscs-cor-backend-pr-526
